# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_Enclos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 468)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_id_7 = QtWidgets.QLabel(Dialog)
        self.label_id_7.setGeometry(QtCore.QRect(20, 70, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        self.label_id_7.setFont(font)
        self.label_id_7.setObjectName("label_id_7")
        self.lineEdit_id_enclos = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_id_enclos.setGeometry(QtCore.QRect(20, 110, 171, 41))
        self.lineEdit_id_enclos.setObjectName("lineEdit_id_enclos")
        self.label_id_8 = QtWidgets.QLabel(Dialog)
        self.label_id_8.setGeometry(QtCore.QRect(20, 210, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        self.label_id_8.setFont(font)
        self.label_id_8.setObjectName("label_id_8")
        self.label_err_id_enclos = QtWidgets.QLabel(Dialog)
        self.label_err_id_enclos.setGeometry(QtCore.QRect(20, 160, 221, 41))
        self.label_err_id_enclos.setObjectName("label_err_id_enclos")
        self.comboBox_habitat_enclos = QtWidgets.QComboBox(Dialog)
        self.comboBox_habitat_enclos.setGeometry(QtCore.QRect(20, 250, 171, 41))
        self.comboBox_habitat_enclos.setObjectName("comboBox_habitat_enclos")
        self.label_id_9 = QtWidgets.QLabel(Dialog)
        self.label_id_9.setGeometry(QtCore.QRect(20, 310, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        self.label_id_9.setFont(font)
        self.label_id_9.setObjectName("label_id_9")
        self.comboBox_dimension_enclos = QtWidgets.QComboBox(Dialog)
        self.comboBox_dimension_enclos.setGeometry(QtCore.QRect(20, 350, 171, 41))
        self.comboBox_dimension_enclos.setObjectName("comboBox_dimension_enclos")
        self.listView_2 = QtWidgets.QListView(Dialog)
        self.listView_2.setGeometry(QtCore.QRect(250, 111, 281, 281))
        self.listView_2.setObjectName("listView_2")
        self.label_id_10 = QtWidgets.QLabel(Dialog)
        self.label_id_10.setGeometry(QtCore.QRect(250, 70, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        self.label_id_10.setFont(font)
        self.label_id_10.setObjectName("label_id_10")
        self.button_quitter_enclos = QtWidgets.QPushButton(Dialog)
        self.button_quitter_enclos.setGeometry(QtCore.QRect(320, 410, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(16)
        self.button_quitter_enclos.setFont(font)
        self.button_quitter_enclos.setObjectName("button_quitter_enclos")
        self.button_creer_enclos = QtWidgets.QPushButton(Dialog)
        self.button_creer_enclos.setGeometry(QtCore.QRect(20, 410, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        self.button_creer_enclos.setFont(font)
        self.button_creer_enclos.setObjectName("button_creer_enclos")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Enclos"))
        self.label_7.setText(_translate("Dialog", "Création d\'un enclos"))
        self.label_id_7.setText(_translate("Dialog", "Numero de l\'enclos"))
        self.label_id_8.setText(_translate("Dialog", "Habitat naturel"))
        self.label_err_id_enclos.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">Longueur de l\'id de l\'animal doit être égal à 7 </span></p><p><span style=\" color:#ff0000;\">et composée seulement de numéro</span></p></body></html>"))
        self.label_id_9.setText(_translate("Dialog", "Dimension de l\'enclos"))
        self.label_id_10.setText(_translate("Dialog", "Liste des enclos"))
        self.button_quitter_enclos.setText(_translate("Dialog", "Menu principale"))
        self.button_creer_enclos.setText(_translate("Dialog", "Créer"))
