# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(224, 403)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 40, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.button_Animal_main = QtWidgets.QPushButton(self.centralwidget)
        self.button_Animal_main.setGeometry(QtCore.QRect(30, 110, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(16)
        self.button_Animal_main.setFont(font)
        self.button_Animal_main.setObjectName("button_Animal_main")
        self.button_Enclos_main = QtWidgets.QPushButton(self.centralwidget)
        self.button_Enclos_main.setGeometry(QtCore.QRect(30, 190, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(16)
        self.button_Enclos_main.setFont(font)
        self.button_Enclos_main.setObjectName("button_Enclos_main")
        self.button_Quitter_main = QtWidgets.QPushButton(self.centralwidget)
        self.button_Quitter_main.setGeometry(QtCore.QRect(30, 270, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(16)
        self.button_Quitter_main.setFont(font)
        self.button_Quitter_main.setObjectName("button_Quitter_main")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 224, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Zoo"))
        self.button_Animal_main.setText(_translate("MainWindow", "Animal"))
        self.button_Enclos_main.setText(_translate("MainWindow", "Enclos"))
        self.button_Quitter_main.setText(_translate("MainWindow", "Quitter"))
